
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#093545")


canvas = Canvas(
    window,
    bg = "#093545",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    664.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=737.0,
    y=554.0,
    width=59.0,
    height=21.0
)

canvas.create_text(
    491.0,
    554.0,
    anchor="nw",
    text="Do you have an account?",
    fill="#FFFFFF",
    font=("Montserrat Medium", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=491.0,
    y=486.0,
    width=300.0,
    height=45.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    641.0,
    436.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#224957",
    highlightthickness=0
)
entry_1.place(
    x=501.0,
    y=414.0,
    width=280.0,
    height=43.0
)

canvas.create_text(
    491.0,
    394.0,
    anchor="nw",
    text="Confirm password",
    fill="#FFFFFF",
    font=("LexendDeca Regular", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    641.0,
    359.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#224957",
    highlightthickness=0
)
entry_2.place(
    x=501.0,
    y=337.0,
    width=280.0,
    height=43.0
)

canvas.create_text(
    491.0,
    317.0,
    anchor="nw",
    text="Passoword",
    fill="#FFFFFF",
    font=("LexendDeca Regular", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    641.0,
    282.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#224957",
    highlightthickness=0
)
entry_3.place(
    x=501.0,
    y=260.0,
    width=280.0,
    height=43.0
)

canvas.create_text(
    491.0,
    240.0,
    anchor="nw",
    text="Email",
    fill="#FFFFFF",
    font=("LexendDeca Regular", 14 * -1)
)

canvas.create_text(
    459.0,
    203.0,
    anchor="nw",
    text="Sign up to start managing student information",
    fill="#FFFFFF",
    font=("LexendDeca Regular", 16 * -1)
)

canvas.create_text(
    530.0,
    93.0,
    anchor="nw",
    text="Sign up",
    fill="#FFFFFF",
    font=("LexendDeca ExtraLight", 64 * -1)
)
window.resizable(False, False)
window.mainloop()
